# We use the official Python images. This may need to get locked in, or back to Ubuntu at some point
FROM node

RUN mkdir /code

WORKDIR /code
COPY . .

RUN npm install
RUN node_modules/.bin/bower --allow-root install
RUN node_modules/.bin/grunt build

# This file needs to be outside the /code dir as it's mounted  durin development
RUN cp docker/dev/docker-entrypoint.sh.npm ./docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["npm", "watch"]
