[pytest]
DJANGO_SETTINGS_MODULE=config.settings.local
testpaths = socialhome
env =
    TEST=1
asyncio_mode = auto
#asyncio_default_test_loop_scope = session
#asyncio_default_fixture_loop_scope = session
