# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_guid_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
    ]
