# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_unique_index_on_user_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rsa_private_key',
            field=models.TextField(editable=False, null=True, verbose_name='RSA private key'),
        ),
        migrations.AddField(
            model_name='user',
            name='rsa_public_key',
            field=models.TextField(editable=False, null=True, verbose_name='RSA public key'),
        ),
    ]
