# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_rsa_key_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='local',
            field=models.BooleanField(default=True, editable=False, verbose_name='Local'),
        ),
    ]
