# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 22:03
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import socialhome.enums


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visibility',
            field=enumfields.fields.EnumIntegerField(default=3, enum=socialhome.enums.Visibility, verbose_name='Profile visibility'),
        ),
    ]
