# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trusted_editor',
            field=models.BooleanField(default=False, verbose_name='Trusted editor'),
        ),
    ]
