# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 19:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_populate_user_handles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(editable=False, max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Handle'),
        ),
    ]
