# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_move_users_content_to_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='user',
            name='local',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rsa_private_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rsa_public_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='visibility',
        ),
    ]
