# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_fields_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(editable=False, help_text='Usually username, for local users at least.', max_length=64, unique=True, verbose_name='Nickname'),
        ),
    ]
