# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_make_profile_nickname_not_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
