# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_followers_and_following_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='following_set', to='users.Profile', verbose_name='Followers'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers_set', to='users.Profile', verbose_name='Following'),
        ),
    ]
