# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_related_names_for_legacy_user_follow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='_profile_following_+', to='users.Profile', verbose_name='Following'),
        ),
    ]
