# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_fill_missing_profile_images_with_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='users.Profile', verbose_name='Following'),
        ),
    ]
