# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_make_profile_following_asymmetrical'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='picture_height', max_length=255, null=True, upload_to='profiles/', verbose_name='Picture', width_field='picture_width'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Picture height'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Picture width'),
        ),
    ]
