# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 21:29
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_picture_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Picture PPOI'),
        ),
    ]
