# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_make_new_stream_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='Handle'),
        ),
    ]
