# Generated by Django 2.0.5 on 2018-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_django2_extend_user_last_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fid',
            field=models.URLField(editable=False, max_length=255, null=True, unique=True, verbose_name='Federation ID'),
        ),
    ]
