# Generated by Django 2.0.8 on 2018-09-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_django2_extend_user_last_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fid',
            field=models.URLField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Federation ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(unique=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guid',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Handle'),
        ),
    ]
