# Generated by Django 2.0.8 on 2018-09-16 17:22
from uuid import uuid4

from django.conf import settings
from django.db import migrations
from django.db.migrations import RunPython
from django.urls import reverse


def forward(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.select_related('user').iterator():
        if profile.user:
            profile.uuid = profile.guid
            url = reverse("users:profile-detail", kwargs={"uuid": profile.uuid})
            fid = f"{settings.SOCIALHOME_URL}{url}"
            Profile.objects.filter(id=profile.id).update(uuid=profile.uuid, fid=fid)
        else:
            Profile.objects.filter(id=profile.id).update(uuid=uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_refactored_federation_ids'),
    ]

    operations = [
        RunPython(forward, RunPython.noop)
    ]
