# Generated by Django 2.0.5 on 2018-07-26 18:03
from django.conf import settings
from django.db import migrations
from django.db.migrations import RunPython
from django.urls import reverse
from federation.utils.diaspora import generate_diaspora_profile_id


def forward(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.all().iterator():
        if profile.user is not None:
            # Local
            # TODO shoudl this be changed to the new uuid field?
            url = reverse('users:profile-detail', kwargs={'guid': profile.guid})
            fid = f"{settings.SOCIALHOME_URL}{url}"
        else:
            # Diaspora remote
            fid = generate_diaspora_profile_id(profile.handle, profile.guid)
        Profile.objects.filter(id=profile.id).update(fid=fid)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_profile_fid'),
    ]

    operations = [
        RunPython(forward, RunPython.noop)
    ]
