# Generated by Django 2.0.5 on 2018-07-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_populate_profile_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fid',
            field=models.URLField(editable=False, max_length=255, unique=True, verbose_name='Federation ID'),
        ),
    ]
