# Generated by Django 2.0.8 on 2019-02-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_make_profile_uuid_editable_false'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
