# Generated by Django 2.0.13 on 2019-02-28 20:50

from django.db import migrations
import enumfields.fields
import socialhome.enums


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_profile_followed_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visibility',
            field=enumfields.fields.EnumIntegerField(default=0, enum=socialhome.enums.Visibility, verbose_name='Profile visibility'),
        ),
    ]
