# Generated by Django 2.0.5 on 2018-08-01 21:08
import uuid

from django.db import migrations
from django.db.migrations import RunPython


def forward(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.all().iterator():
        profile.uuid = str(uuid.uuid4())
        Profile.objects.filter(id=profile.id).update(uuid=profile.uuid)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_profile_uuid'),
    ]

    operations = [
        RunPython(forward, RunPython.noop)
    ]
