# Generated by Django 2.0.13 on 2019-03-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_set_profile_default_visibility_to_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inbox_private',
            field=models.URLField(blank=True, verbose_name='Private inbox'),
        ),
        migrations.AddField(
            model_name='profile',
            name='inbox_public',
            field=models.URLField(blank=True, verbose_name='Public inbox'),
        ),
    ]
