# Generated by Django 2.2.12 on 2020-05-02 21:15

from django.db import migrations
from django.db.migrations import RunPython


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_repopulate_profile_private_inbox'),
    ]

    operations = [
        RunPython(RunPython.noop, RunPython.noop)
    ]
