# Generated by Django 2.2.28 on 2022-11-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_merge_protocol_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finger',
            field=models.URLField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Webfinger subject'),
        ),
    ]
