# Generated by Django 2.2.24 on 2022-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20221114_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url_large',
            field=models.URLField(blank=True, max_length=500, verbose_name='Image - large'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url_medium',
            field=models.URLField(blank=True, max_length=500, verbose_name='Image - medium'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url_small',
            field=models.URLField(blank=True, max_length=500, verbose_name='Image - small'),
        ),
    ]
