# Generated by Django 2.2.28 on 2023-02-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20221220_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_approved',
            field=models.NullBooleanField(default=None, verbose_name='Admin approved'),
        ),
    ]
