# Generated by Django 2.2.28 on 2023-02-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_user_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_request_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Account request reason'),
        ),
    ]
