# Generated by Django 3.2.18 on 2023-04-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_user_account_request_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers_fid',
            field=models.URLField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='AP Followers FID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='key_id',
            field=models.URLField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='AP Public Key ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
