# Generated by Django 3.2.18 on 2024-01-02 16:03

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_profile_remote_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(django.db.models.functions.text.Upper('finger'), name='users_profile_finger_upper'),
        ),
    ]
