# Generated by Django 3.2.18 on 2024-05-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_profile_users_profile_finger_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Picture'),
        ),
    ]
