# Generated by Django 3.2.18 on 2025-11-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20240526_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_approved',
            field=models.BooleanField(default=None, null=True, verbose_name='Admin approved'),
        ),
    ]
