# Generated by Django 4.2.26 on 2025-12-30 19:50

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_user_admin_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visibility',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Limited'), (2, 'Site'), (3, 'Self')], default=0, verbose_name='Profile visibility'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('visibility__in', [0, 1, 2, 3])), name='users_Profile_visibility_Visibility'),
        ),
    ]
