# Generated by Django 4.2.26 on 2026-01-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_profile_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rendered_bio',
            field=models.TextField(blank=True, verbose_name='Rendered bio'),
        ),
    ]
