# Generated by Django 4.2.26 on 2026-01-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_profile_rendered_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url_large',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Image - large'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url_medium',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Image - medium'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url_small',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Image - small'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Picture'),
        ),
    ]
