# Generated by Django 4.2.26 on 2026-02-09 19:08

import django.contrib.postgres.fields
from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0054_alter_profile_avatar_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="protocols",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django_enum.fields.EnumPositiveSmallIntegerField(
                    choices=[(0, "ACTIVITYPUB"), (1, "DIASPORA"), (2, "MATRIX")]
                ),
                default=list,
                size=None,
            ),
        ),
    ]
