# Generated by Django 4.2.26 on 2026-02-16 17:46

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0055_profile_protocols"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                django.db.models.functions.text.Upper("fid"),
                name="users_profile_fid_upper",
            ),
        ),
    ]
