# Generated by Django 4.2.26 on 2026-03-13 14:56

from django.db import migrations

from federation.protocols.enums import ProtocolType


def populate_protocols(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.filter(user__isnull=False).iterator():
        profile.protocols = [ProtocolType.ACTIVITYPUB, ProtocolType.DIASPORA]
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0056_profile_users_profile_fid_upper"),
    ]

    operations = [
        migrations.RunPython(populate_protocols)
    ]
