# Generated by Django 5.2.16 on 2026-09-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0057_populate_protocols"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="user",
            name="picture_height",
        ),
        migrations.RemoveField(
            model_name="user",
            name="picture_ppoi",
        ),
        migrations.RemoveField(
            model_name="user",
            name="picture_width",
        ),
    ]
