# Generated by Django 2.0.13 on 2019-05-26 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import federation.entities.activitypub.enums
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0038_populate_profile_protocol'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('fid', models.URLField(editable=False, max_length=255, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('type', enumfields.fields.EnumField(enum=federation.entities.activitypub.enums.ActivityType, max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
