# Generated by Django 4.2.26 on 2025-12-30 19:50

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('Accept', 'ACCEPT'), ('Announce', 'ANNOUNCE'), ('Create', 'CREATE'), ('Delete', 'DELETE'), ('Follow', 'FOLLOW'), ('Undo', 'UNDO'), ('Update', 'UPDATE')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['Accept', 'Announce', 'Create', 'Delete', 'Follow', 'Undo', 'Update'])), name='activities_Activity_type_ActivityType'),
        ),
    ]
