# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import socialhome.content.enums
import socialhome.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', enumfields.fields.EnumIntegerField(enum=socialhome.content.enums.ContentTarget)),
                ('object_id', models.PositiveIntegerField()),
                ('visibility', enumfields.fields.EnumIntegerField(default=0, enum=socialhome.enums.Visibility)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Content owner')),
            ],
        ),
    ]
