# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 12:39
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import socialhome.content.enums
import socialhome.enums


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='target',
            field=enumfields.fields.EnumIntegerField(db_index=True, enum=socialhome.content.enums.ContentTarget),
        ),
        migrations.AlterField(
            model_name='content',
            name='visibility',
            field=enumfields.fields.EnumIntegerField(db_index=True, default=0, enum=socialhome.enums.Visibility),
        ),
    ]
