# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_db_indexes_to_content_target_and_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Order'),
        ),
    ]
