# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 20:56
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations import RunPython


def forward(apps, schema_editor):
    Content = apps.get_model("content", "Content")
    Post = apps.get_model("content", "Post")
    for content in Content.objects.all():
        content.author = content.user.profile
        content.save()
    for post in Post.objects.all():
        post.author = post.user.profile
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_add_author_to_content_and_post'),
        ('users', '0013_remove_fields_from_user'),
    ]

    operations = [
        RunPython(forward, RunPython.noop),
    ]
