# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import socialhome.enums


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_user_on_content_and_user_and_make_author_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pinned to profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=enumfields.fields.EnumIntegerField(db_index=True, default=0, enum=socialhome.enums.Visibility),
        ),
    ]
