# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 10:30
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations import RunPython


def forward(apps, schema_editor):
    Content = apps.get_model("content", "Content")
    Post = apps.get_model("content", "Post")
    for content in Content.objects.all():
        post = Post.objects.get(id=content.object_id)
        post.order = content.order
        post.pinned = True if content.target == 0 else False
        post.visibility = content.visibility
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_copy_content_fields_to_post'),
    ]

    operations = [
        RunPython(forward, RunPython.noop),
    ]
