# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_copy_content_content_to_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='author',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='public',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
