# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_content_remove_public_from_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Content',
        ),
    ]
