# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_rename_post_to_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEmbedCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('oembed', models.TextField(verbose_name='OEmbed HTML content')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Modified')),
            ],
        ),
        migrations.CreateModel(
            name='OpenGraphCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.URLField(blank=True, verbose_name='Image URL')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Modified')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='oembed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.OEmbedCache', verbose_name='OEmbed cache'),
        ),
        migrations.AddField(
            model_name='content',
            name='opengraph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.OpenGraphCache', verbose_name='OpenGraph cache'),
        ),
    ]
