# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_add_tag_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='rendered',
            field=models.TextField(blank=True, editable=False, verbose_name='Rendered text'),
        ),
    ]
