# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_content_rendered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='modified',
        ),
    ]
