# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_content_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='share_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='content.Content', verbose_name='Share of'),
        ),
    ]
