# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 20:10
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import socialhome.content.enums


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_content_share_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=enumfields.fields.EnumIntegerField(db_index=True, default=0, editable=False, enum=socialhome.content.enums.ContentType),
        ),
    ]
