# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_fill_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='reply_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Reply count'),
        ),
        migrations.AddField(
            model_name='content',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Shares count'),
        ),
        migrations.AddField(
            model_name='content',
            name='local',
            field=models.BooleanField(default=False, editable=False, verbose_name='Local'),
        ),
    ]
