# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_content_show_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='federate',
            field=models.BooleanField(default=True, help_text='Disable to skip federating this version to remote servers. Note, saved content versionwill still be updated to local streams.', verbose_name='Federate to remote servers'),
        ),
    ]
