# Generated by Django 2.0.3 on 2018-06-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_django2_extend_user_last_name_max_length'),
        ('content', '0024_add_content_federate_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='mentions',
            field=models.ManyToManyField(related_name='mentioned_in', to='users.Profile', verbose_name='Mentions'),
        ),
    ]
