# Generated by Django 2.0.5 on 2018-06-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_django2_extend_user_last_name_max_length'),
        ('content', '0025_add_mentions_to_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='limited_visibilities',
            field=models.ManyToManyField(related_name='limited_visibilities', to='users.Profile', verbose_name='Limitied visibilities'),
        ),
    ]
