# Generated by Django 2.0.5 on 2018-06-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_content_limited_visibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='federate',
            field=models.BooleanField(default=True, help_text='Disable to skip federating this version to remote servers. Note, saved content version will still be updated to local streams.', verbose_name='Federate to remote servers'),
        ),
    ]
