# Generated by Django 2.0.5 on 2018-06-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_fix_help_text_of_content_federate'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='include_following',
            field=models.BooleanField(default=False, help_text='Automatically includes all the people you follow as recipients.', verbose_name='Include people I follow'),
        ),
        migrations.AddField(
            model_name='content',
            name='mention_recipients',
            field=models.BooleanField(default=False, help_text='Mention all recipients. This will make recipients visible to each other.', verbose_name='Mention recipients'),
        ),
    ]
