# Generated by Django 2.0.5 on 2018-07-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_add_content_include_following_and_mention_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='mention_recipients',
        ),
    ]
