# Generated by Django 2.0.5 on 2018-08-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_remove_content_mention_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='fid',
            field=models.URLField(editable=False, max_length=255, null=True, unique=True, verbose_name='Federation ID'),
        ),
        migrations.AddField(
            model_name='content',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='guid',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='GUID'),
        ),
    ]
