# Generated by Django 2.0.5 on 2018-08-01 21:15
import uuid

from django.conf import settings
from django.db import migrations
from django.db.migrations import RunPython
from django.urls import reverse
from federation.utils.diaspora import generate_diaspora_id


TYPE_MAPPINGS = {
    0: "status_message",
    1: "comment",
    2: "reshare",
}


def forward(apps, schema_editor):
    Content = apps.get_model("content", "Content")
    Profile = apps.get_model("users", "Profile")
    for content in Content.objects.all().select_related("author").iterator():
        content.uuid = str(uuid.uuid4())
        if content.local:
            url = reverse("content:view-by-guid", kwargs={"guid": content.uuid})
            fid = f"{settings.SOCIALHOME_URL}{url}"
        else:
            # Diaspora remote
            fid = generate_diaspora_id(
                content.author.handle, TYPE_MAPPINGS.get(content.content_type.value), content.guid,
            )
        Content.objects.filter(id=content.id).update(uuid=content.uuid, fid=fid)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_add_uuid_make_old_unique_fields_optional'),
        ('users', '0035_make_profile_uuid_not_null'),
    ]

    operations = [
        RunPython(forward, RunPython.noop)
    ]
