# Generated by Django 2.0.8 on 2018-09-16 17:12
from uuid import uuid4

from django.conf import settings
from django.db import migrations
from django.db.migrations import RunPython
from django.urls import reverse


TYPE_MAPPINGS = {
    0: "status_message",
    1: "comment",
    2: "reshare",
}


def forward(apps, schema_editor):
    Content = apps.get_model("content", "Content")
    for content in Content.objects.iterator():
        if content.local:
            content.uuid = content.guid
            url = reverse("content:view-by-uuid", kwargs={"uuid": content.uuid})
            fid = f"{settings.SOCIALHOME_URL}{url}"
            Content.objects.filter(id=content.id).update(uuid=content.uuid, fid=fid)
        else:
            content.uuid = uuid4()
            Content.objects.filter(id=content.id).update(uuid=content.uuid)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_refactored_federation_ids'),
    ]

    operations = [
        RunPython(forward, RunPython.noop)
    ]
