# Generated by Django 2.0.5 on 2018-08-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_populate_content_uuid_and_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='fid',
            field=models.URLField(editable=False, max_length=255, unique=True, verbose_name='Federation ID'),
        ),
        migrations.AlterField(
            model_name='content',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
