# Generated by Django 2.0.8 on 2018-08-11 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_make_content_fid_and_uuid_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
