# Generated by Django 2.0.8 on 2019-02-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_make_content_uuid_editable_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
