# Generated by Django 2.0.8 on 2018-09-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_set_content_uuid_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='fid',
            field=models.URLField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Federation ID'),
        ),
    ]
