# Generated by Django 2.1.9 on 2019-07-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_make_tag_uuid_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='root_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_children', to='content.Content', verbose_name='Root parent'),
        ),
    ]
