# Generated by Django 2.2.24 on 2022-12-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_fill_content_root_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='replies_fid',
            field=models.URLField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Reply Collection ID'),
        ),
    ]
