# Generated by Django 2.2.24 on 2022-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_content_replies_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opengraphcache',
            name='image',
            field=models.URLField(blank=True, max_length=500, verbose_name='Image URL'),
        ),
    ]
