# Generated by Django 3.2.18 on 2024-07-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_content_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='has_had_local_replies',
            field=models.BooleanField(default=False, verbose_name='Has root content had local replies'),
        ),
    ]
