# Generated by Django 4.2.26 on 2025-12-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_alter_content_through'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='local',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Local'),
        ),
    ]
