# Generated by Django 4.2.26 on 2025-12-30 19:50

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_alter_content_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Content'), (1, 'Reply'), (2, 'Share')], db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='visibility',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Limited'), (2, 'Site'), (3, 'Self')], db_index=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.CheckConstraint(check=models.Q(('visibility__in', [0, 1, 2, 3])), name='content_Content_visibility_Visibility'),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.CheckConstraint(check=models.Q(('content_type__in', [0, 1, 2])), name='content_Content_content_type_ContentType'),
        ),
    ]
