# Generated by Django 4.2.26 on 2026-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0045_alter_content_content_type_alter_content_visibility_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="sensitive",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                verbose_name="Sensitive content",
            ),
        ),
    ]
