# Generated by Django 4.2.26 on 2026-03-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0046_content_sensitive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="sensitive",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Sensitive content"
            ),
        ),
    ]
