# Generated by Django 5.2.16 on 2026-08-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0047_alter_content_sensitive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="fid",
            field=models.URLField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Federation ID",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="guid",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="GUID",
            ),
        ),
    ]
