# Generated by Django 2.0.3 on 2018-06-09 14:04

from django.db import migrations, models
import django.utils.timezone
import django_fsm
import enumfields.fields
import markdownx.models
import model_utils.fields
import socialhome.enums


class Migration(migrations.Migration):

    dependencies = [
        ('socialhome', '0002_default_robots_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', markdownx.models.MarkdownxField()),
                ('version', models.DateTimeField(auto_now=True)),
                ('published_content', markdownx.models.MarkdownxField(blank=True, editable=False)),
                ('published_version', models.DateTimeField(editable=False, null=True)),
                ('state', django_fsm.FSMField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=50)),
                ('type', enumfields.fields.EnumField(enum=socialhome.enums.PolicyDocumentType, max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
