# Generated by Django 3.2.18 on 2024-12-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialhome', '0005_mediaupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='Upload Category'),
        ),
    ]
