# Generated by Django 3.2.18 on 2025-01-09 12:54

from django.db import migrations, models
import socialhome.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialhome', '0006_mediaupload_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=socialhome.models.media_file_name),
        ),
    ]
