# Generated by Django 4.2.26 on 2025-12-30 19:50

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialhome', '0007_alter_mediaupload_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydocument',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('tos', 'Terms of service'), ('privacypolicy', 'Privacy policy')], max_length=30, unique=True),
        ),
        migrations.AddConstraint(
            model_name='policydocument',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['tos', 'privacypolicy'])), name='socialhome_PolicyDocument_type_PolicyDocumentType'),
        ),
    ]
