# Generated by Django 4.2.29 on 2026-03-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialhome", "0008_alter_policydocument_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PolicyDocument",
        ),
    ]
