# Generated by Django 2.1.9 on 2019-06-27 20:12

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('entities_found', models.PositiveSmallIntegerField()),
                ('headers', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('protocol', models.CharField(max_length=30)),
                ('sender', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
    ]
