# Generated by Django 2.2.10 on 2020-02-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=8),
            preserve_default=False,
        ),
    ]
